### ISSUE TITLE
Incredible work, thank you for making this dude

### ISSUE THREAD

**Issue by Baggydawg** [c-stephens/Call-or-Message-Contact#1]
Hi mate,

I don't actually have any issues with this workflow, I just wanted to leave a message of thanks for creating it.

It works perfectly and saves me such a huge amount of time. So a huge thanks to you and really appreciate you making the big sur update to the previous one you'd made. Peace man!

**Comment by c-stephens** [comment]
Thank you, I am just glad people are even using it lol.
